Add correlation coefficient
thrasher-corp/gct-ta pull request #1
Opened 2020-06-19 01:36 UTC by thrasher-

Add support for correlation coefficient

2020-06-19 05:06 UTC, shazbert requested changes
Legendary! 👍 Just some basic nitorinos.

2020-06-19 05:06 UTC, shazbert commented on indicators/correlation.go
> +func CorrelationCoefficient(c1, c2 []float64, period int) []float64 {
Comment exported function

2020-06-19 05:06 UTC, shazbert commented on indicators/correlation.go
> +	}
can just do:
```go
for x := period - 1; x < c1Len; x++ {
		idx := x + 1
		r[x] = correlation(c1[idx-period:idx], c2[idx-period:idx])
	}
```

2020-06-19 05:27 UTC, shazbert approved these changes
🥇 tACK

2020-06-19 07:53 UTC, MadCozBadd approved these changes
tACK!!!!!!!!!!!!!!!

2020-06-21 23:48 UTC, gloriousCode requested changes
Looks all good! 🎉  Could you please add support to  `./cmd/gct-ta` cli?

2020-06-23 04:06 UTC, MadCozBadd approved these changes
LGTM

2020-06-23 04:31 UTC, gloriousCode approved these changes
Thanks for making those changes! tACK!

2020-06-23 04:37 UTC, shazbert approved these changes
tACK - One out of scope thing to implement. I couldn't match it on TV but I think that might be due to cryptowat.ch values.

2020-06-23 04:37 UTC, shazbert commented on cmd/gct-ta/main.go
> +		out[0] = gctta.CorrelationCoefficient(ohlcvData[0].close, ohlcvData[1].close, timeInput)
out of scope:
```
default:
return output{}, fmt.Errorf("indicator %s is not handled", indicator)
```

2020-06-23 06:51 UTC, shazbert approved these changes
new changes tACK!

2020-06-23 06:52 UTC, gloriousCode approved these changes
tACK new changes!
# 🎲 🦄  🐧

2020-06-23 07:15 UTC, MadCozBadd approved these changes
tACK

2020-06-23 07:27 UTC, merged